import { useState, useEffect } from 'react';
import { api } from '../../lib/api';
import { 
  Copy, Check, Users, PackageCheck, Wallet, Link2, 
  Search, ShieldAlert, Award, RefreshCw, UserCheck,
  ArrowDownToLine, Building2, CreditCard, Clock, CheckCircle2, XCircle, X, FileText
} from 'lucide-react';
import toast from 'react-hot-toast';
import { motion, AnimatePresence } from 'framer-motion';
import { useLanguage } from '../../contexts/LanguageContext';

interface InvitedUser {
  id: number;
  uuid: string;
  fullName: string;
  email: string;
  phone: string;
  role: string;
  isActive: boolean;
  isAffiliateInvite?: boolean;
  createdAt: string;
  totalLeads: number;
  deliveredLeads: number;
  earningsGenerated: number;
}

interface PayoutItem {
  id: number;
  amountMad: number;
  bankName: string;
  ribAccount: string;
  status: string;
  createdAt: string;
  processedAt?: string;
}

interface AffiliateStats {
  referralCode: string;
  canManageAffiliateInvites: boolean;
  commissionPerDeliveredLead: number;
  totalInvitedUsers: number;
  totalLeads: number;
  deliveredLeads: number;
  totalEarnings: number;
  withdrawnEarnings: number;
  pendingEarnings: number;
  availableEarnings: number;
  defaultBankName: string;
  defaultRibAccount: string;
  payoutHistory: PayoutItem[];
  invitedUsers: InvitedUser[];
}

const translations = {
  ar: {
    badge: "برنامج التسويق بالعمولة للمساعدين",
    title: "احصل على عمولة مقابل كل طلبيّة مسلّمة",
    desc: (rate: number) => `شارِك رابط الدعوة الخاص بك. احصل على ${rate} درهم لكل طلبية تم تأكيدها وتسليمها من طرف المدعوين من طرفك.`,
    refresh: "تحديث",
    dataRefreshed: "تم تحديث البيانات",
    loadErr: "حدث خطأ أثناء تحميل البيانات",
    accessDisabledTitle: "تم تعطيل إذن رابط الدعوة",
    accessDisabledDesc: "إذن التسويق بالعمولة معطل حاليًا لحسابك. تواصل مع المسؤول لتفعيل حسابك وتوليد روابط الدعوة.",
    inviteLinkTitle: "رابط الدعوة الخاص بك",
    inviteLinkDesc: "شارِك هذا الرابط لتسجيل مستخدمين جدد كمدعوين",
    active: "مفعّل",
    copy: "نسخ",
    copied: "تم النسخ!",
    invitedAccounts: "الحسابات المدعوة",
    vendorsCreators: "بائعون وصناع محتوى",
    deliveredLeads: "الطلبيات المسلمة",
    successfulDeliveries: "التسليمات الناجحة من مدعويك",
    commissionPerLead: "العمولة / طلبية",
    rateSetByAdmin: "النسبة المحددة من الإدارة",
    withdrawableEarnings: "الأرباح القابلة للسحب",
    pending: "درهم قيد الانتظار",
    withdrawGains: "سحب أرباحي",
    min50dh: "(الحد الأدنى 50 درهم)",
    payoutHistoryTitle: "سجل طلبات السحب",
    id: "المعرّف",
    amount: "المبلغ",
    bank: "البنك",
    status: "الحالة",
    date: "التاريخ",
    statusPending: "قيد الانتظار",
    statusCompleted: "تم الدفع",
    statusRejected: "مرفوض",
    statusReceived: "مستلم",
    registeredUsersTitle: "قائمة الحسابات المسجلة",
    registeredUsersDesc: "سجل المستخدمين الذين انضموا عبر رابط الدعوة الخاص بك",
    searchPlaceholder: "البحث بالاسم أو البريد الإلكتروني...",
    user: "المستخدم",
    role: "الدور",
    origin: "المصدر",
    regDate: "تاريخ التسجيل",
    totalLeads: "إجمالي الطلبيات",
    deliveredLeadsCol: "الطلبيات المسلمة",
    generatedComm: "العمولة المحققة",
    vendor: "بائع",
    creator: "صانع محتوى",
    viaLink: "✨ مدعو عبر الرابط",
    adminAssign: "👤 تعيين الإدارة",
    noUsersFound: "لم يتم العثور على أي مستخدم",
    noUsersFoundSub: "شارِك رابطك لرؤية المستخدمين الجدد هنا.",
    modalTitle: "طلب سحب الأرباح",
    modalDesc: "اسحب أرباحك مباشرة إلى حسابك البنكي.",
    withdrawableBalance: "الرصيد القابل للسحب",
    amountToWithdraw: "المبلغ المراد سحبه (درهم)",
    minWithdrawMessage: "الحد الأدنى للسحب:",
    bankName: "اسم البنك",
    bankNamePlaceholder: "مثال: CIH Bank, Attijariwafa, BCP...",
    ribNumber: "رقم الحساب البنكي RIB (24 رقم)",
    ribDigitsOnly: "أرقام فقط (بدون مسافات)",
    cancel: "إلغاء",
    confirmWithdrawal: "تأكيد السحب",
    withdrawSuccess: "تم تقديم طلب السحب بنجاح!",
    minSoldeErr: "الرصيد الأدنى المطلوب للسحب هو 50 درهم.",
    minAmountErr: "الحد الأدنى للسحب هو 50 درهم",
    exceedSoldeErr: "المبلغ المطلوب يتجاوز رصيدك المتاح",
    bankRequiredErr: "يرجى إدخال اسم البنك",
    rib24Err: "يجب أن يتكون رقم RIB من 24 رقمًا بالضبط"
  },
  en: {
    badge: "Helper Affiliate Program",
    title: "Earn on Every Delivered Lead",
    desc: (rate: number) => `Share your unique invitation link. Receive ${rate} DH for every validated and delivered lead generated by your invited users.`,
    refresh: "Refresh",
    dataRefreshed: "Data refreshed",
    loadErr: "Error loading statistics",
    accessDisabledTitle: "Affiliate Link Access Disabled",
    accessDisabledDesc: "Affiliate invitation permission is currently disabled for your Helper account. Contact an administrator to enable your access and generate invitation links.",
    inviteLinkTitle: "Your Invitation Link",
    inviteLinkDesc: "Share this link to register new users as your invitees",
    active: "Active",
    copy: "Copy",
    copied: "Copied!",
    invitedAccounts: "Invited Accounts",
    vendorsCreators: "Vendors & Creators",
    deliveredLeads: "Delivered Leads",
    successfulDeliveries: "Successful deliveries by your invitees",
    commissionPerLead: "Commission / Lead",
    rateSetByAdmin: "Rate set by administration",
    withdrawableEarnings: "Withdrawable Earnings",
    pending: "DH pending",
    withdrawGains: "Withdraw Earnings",
    min50dh: "(Min. 50 DH)",
    payoutHistoryTitle: "Withdrawal Request History",
    id: "ID",
    amount: "Amount",
    bank: "Bank",
    status: "Status",
    date: "Date",
    statusPending: "Pending",
    statusCompleted: "Paid",
    statusRejected: "Rejected",
    statusReceived: "Received",
    registeredUsersTitle: "Registered Accounts List",
    registeredUsersDesc: "History of users who joined the platform via your invitation link",
    searchPlaceholder: "Search by name, email...",
    user: "User",
    role: "Role",
    origin: "Origin",
    regDate: "Registration Date",
    totalLeads: "Total Leads",
    deliveredLeadsCol: "Delivered Leads",
    generatedComm: "Generated Commission",
    vendor: "Vendor",
    creator: "Creator",
    viaLink: "✨ Invited via Link",
    adminAssign: "👤 Admin Assignment",
    noUsersFound: "No users found",
    noUsersFoundSub: "Share your link to see your first users appear here.",
    modalTitle: "Withdrawal Request",
    modalDesc: "Withdraw your affiliate earnings directly to your bank account.",
    withdrawableBalance: "Withdrawable Balance",
    amountToWithdraw: "Amount to withdraw (DH)",
    minWithdrawMessage: "Minimum withdrawal amount:",
    bankName: "Bank Name",
    bankNamePlaceholder: "e.g. CIH Bank, Attijariwafa, BCP...",
    ribNumber: "RIB Number (24 digits)",
    ribDigitsOnly: "Digits only (no spaces)",
    cancel: "Cancel",
    confirmWithdrawal: "Confirm Withdrawal",
    withdrawSuccess: "Withdrawal request submitted successfully!",
    minSoldeErr: "Minimum balance required for withdrawal is 50 DH.",
    minAmountErr: "Minimum withdrawal amount is 50 DH",
    exceedSoldeErr: "Requested amount exceeds your available balance",
    bankRequiredErr: "Please fill in the bank name",
    rib24Err: "RIB number must be exactly 24 digits"
  },
  fr: {
    badge: "Programme d'Affiliation Helper",
    title: "Gagnez sur chaque Lead Livré",
    desc: (rate: number) => `Partagez votre lien d'invitation unique. Recevez ${rate} DH pour chaque lead validé et livré généré par vos utilisateurs invités.`,
    refresh: "Actualiser",
    dataRefreshed: "Données actualisées",
    loadErr: "Erreur lors du chargement des statistiques",
    accessDisabledTitle: "Accès au lien d'affiliation désactivé",
    accessDisabledDesc: "L'autorisation de parrainage affilié est actuellement désactivée pour votre compte Helper. Contactez un administrateur pour activer votre accès et générer des liens d'invitation.",
    inviteLinkTitle: "Votre Lien d'Invitation",
    inviteLinkDesc: "Partagez ce lien pour inscrire de nouveaux utilisateurs",
    active: "Actif",
    copy: "Copier",
    copied: "Copié !",
    invitedAccounts: "Comptes Invités",
    vendorsCreators: "Vendeurs & Créateurs",
    deliveredLeads: "Leads Livrés",
    successfulDeliveries: "Livraisons réussies par vos invités",
    commissionPerLead: "Commission / Lead",
    rateSetByAdmin: "Taux fixé par l'administration",
    withdrawableEarnings: "Gains Retirables",
    pending: "DH en attente",
    withdrawGains: "Retirer mes Gains",
    min50dh: "(Min. 50 DH)",
    payoutHistoryTitle: "Historique des Demandes de Retrait",
    id: "ID",
    amount: "Montant",
    bank: "Banque",
    status: "Statut",
    date: "Date",
    statusPending: "En attente",
    statusCompleted: "Payé",
    statusRejected: "Rejeté",
    statusReceived: "Reçu",
    registeredUsersTitle: "Liste des Comptes Inscrits",
    registeredUsersDesc: "Historique des utilisateurs ayant rejoint la plateforme via votre lien",
    searchPlaceholder: "Rechercher par nom, email...",
    user: "Utilisateur",
    role: "Rôle",
    origin: "Origine",
    regDate: "Date d'inscription",
    totalLeads: "Leads Totaux",
    deliveredLeadsCol: "Leads Livrés",
    generatedComm: "Commission Générée",
    vendor: "Vendeur",
    creator: "Créateur",
    viaLink: "✨ Invité via Lien",
    adminAssign: "👤 Assignation Admin",
    noUsersFound: "Aucun utilisateur trouvé",
    noUsersFoundSub: "Partagez votre lien pour voir apparaitre vos premiers utilisateurs ici.",
    modalTitle: "Demande de Retrait",
    modalDesc: "Retirez vos gains d'affiliation directement sur votre compte bancaire.",
    withdrawableBalance: "Solde Retirable",
    amountToWithdraw: "Montant à retirer (DH)",
    minWithdrawMessage: "Montant minimum de retrait:",
    bankName: "Nom de la Banque",
    bankNamePlaceholder: "ex: CIH Bank, Attijariwafa, BCP...",
    ribNumber: "Numéro RIB (24 chiffres)",
    ribDigitsOnly: "Chiffres uniquement (sans espaces)",
    cancel: "Annuler",
    confirmWithdrawal: "Confirmer le Retrait",
    withdrawSuccess: "Demande de retrait soumise avec succès !",
    minSoldeErr: "Le solde minimum requis pour effectuer un retrait est de 50 DH.",
    minAmountErr: "Le montant minimum de retrait est de 50 DH",
    exceedSoldeErr: "Le montant demandé dépasse votre solde disponible",
    bankRequiredErr: "Veuillez renseigner le nom de la banque",
    rib24Err: "Le numéro RIB doit comporter exactement 24 chiffres"
  }
};

export default function HelperAffiliate() {
  const { language } = useLanguage();
  const t = translations[language as 'ar' | 'en' | 'fr'] || translations.fr;

  const [stats, setStats] = useState<AffiliateStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [refreshing, setRefreshing] = useState(false);

  // Withdrawal modal state
  const [showWithdrawModal, setShowWithdrawModal] = useState(false);
  const [withdrawAmount, setWithdrawAmount] = useState<number | string>('');
  const [bankName, setBankName] = useState('');
  const [ribAccount, setRibAccount] = useState('');
  const [submittingWithdraw, setSubmittingWithdraw] = useState(false);

  const fetchStats = async (isManualRefresh = false) => {
    if (isManualRefresh) setRefreshing(true);
    try {
      const res = await api.get('/helper/affiliate/stats');
      const data: AffiliateStats = res.data.data;
      setStats(data);
      if (data.defaultBankName && !bankName) setBankName(data.defaultBankName);
      if (data.defaultRibAccount && !ribAccount) setRibAccount(data.defaultRibAccount);
      if (isManualRefresh) toast.success(t.dataRefreshed);
    } catch (err: any) {
      toast.error(err.response?.data?.message || t.loadErr);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchStats();
  }, []);

  const referralUrl = stats?.referralCode 
    ? `${window.location.origin}/register?ref=${stats.referralCode}`
    : '';

  const handleCopyLink = () => {
    if (!referralUrl) return;
    navigator.clipboard.writeText(referralUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleOpenWithdrawModal = () => {
    if (!stats) return;
    if (stats.availableEarnings < 50) {
      toast.error(t.minSoldeErr);
      return;
    }
    setWithdrawAmount(stats.availableEarnings);
    if (stats.defaultBankName) setBankName(stats.defaultBankName);
    if (stats.defaultRibAccount) setRibAccount(stats.defaultRibAccount);
    setShowWithdrawModal(true);
  };

  const handleWithdrawSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const amount = Number(withdrawAmount);
    if (!amount || amount < 50) {
      toast.error(t.minAmountErr);
      return;
    }
    if (amount > (stats?.availableEarnings || 0)) {
      toast.error(t.exceedSoldeErr);
      return;
    }
    if (!bankName.trim()) {
      toast.error(t.bankRequiredErr);
      return;
    }
    const cleanRib = ribAccount.replace(/\D/g, '');
    if (cleanRib.length !== 24) {
      toast.error(t.rib24Err);
      return;
    }

    setSubmittingWithdraw(true);
    try {
      await api.post('/helper/affiliate/withdraw', {
        amountMad: amount,
        bankName: bankName.trim(),
        ribAccount: cleanRib
      });
      toast.success(t.withdrawSuccess);
      setShowWithdrawModal(false);
      fetchStats();
    } catch (err: any) {
      toast.error(err.response?.data?.message || t.loadErr);
    } finally {
      setSubmittingWithdraw(false);
    }
  };

  const filteredUsers = stats?.invitedUsers?.filter(u => 
    u.fullName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    u.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (u.phone && u.phone.includes(searchTerm))
  ) || [];

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
      </div>
    );
  }

  return (
    <div className="space-y-8 p-4 sm:p-6 lg:p-8 max-w-7xl mx-auto font-['29LT_Kaff',_Inter,_sans-serif] bg-slate-50/50 min-h-screen">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white border border-slate-200/80 p-6 sm:p-8 rounded-3xl text-slate-900 shadow-sm relative overflow-hidden">
        <div className="space-y-2 relative z-10">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-primary-50 text-primary-700 text-xs font-bold border border-primary-200/80">
            <Award className="w-4 h-4 text-primary-600" />
            {t.badge}
          </div>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
            {t.title}
          </h1>
          <p className="text-slate-600 text-sm max-w-2xl leading-relaxed font-medium">
            {t.desc(stats?.commissionPerDeliveredLead || 5)}
          </p>
        </div>

        <button
          onClick={() => fetchStats(true)}
          disabled={refreshing}
          className="inline-flex items-center justify-center gap-2 px-5 py-3 rounded-2xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-sm transition-all border border-slate-200 self-start md:self-auto shadow-sm active:scale-95"
        >
          <RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin text-primary-600' : 'text-slate-500'}`} />
          <span>{t.refresh}</span>
        </button>
      </div>

      {/* Access Control Notice if permission disabled */}
      {!stats?.canManageAffiliateInvites && (
        <motion.div 
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 sm:p-5 rounded-2xl bg-amber-50 border border-amber-200 text-amber-900 flex items-start gap-4 shadow-sm"
        >
          <ShieldAlert className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
          <div className="space-y-1 text-sm">
            <p className="font-bold text-amber-900">{t.accessDisabledTitle}</p>
            <p className="text-amber-800">
              {t.accessDisabledDesc}
            </p>
          </div>
        </motion.div>
      )}

      {/* Referral Link & Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
        {/* Referral Link Card */}
        <div className="md:col-span-2 bg-white rounded-3xl p-6 border border-slate-200/80 shadow-sm flex flex-col justify-between space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-3 rounded-2xl bg-primary-50 text-primary-600 border border-primary-100">
                <Link2 className="w-6 h-6" />
              </div>
              <div>
                <h3 className="font-extrabold text-slate-900 text-base">{t.inviteLinkTitle}</h3>
                <p className="text-xs font-medium text-slate-500">{t.inviteLinkDesc}</p>
              </div>
            </div>
            <span className="px-3 py-1 text-xs font-extrabold rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200/80">
              {t.active}
            </span>
          </div>

          <div className="flex items-center gap-2">
            <input
              type="text"
              readOnly
              value={referralUrl}
              className="flex-1 bg-slate-50 border border-slate-200 rounded-2xl px-4 py-3 text-sm text-slate-800 font-mono font-semibold outline-none focus:border-primary-500 focus:bg-white transition-all"
            />
            <button
              onClick={handleCopyLink}
              disabled={!stats?.canManageAffiliateInvites}
              className={`inline-flex items-center gap-2 px-5 py-3 rounded-2xl font-bold text-sm transition-all shadow-md ${
                copied
                  ? 'bg-emerald-600 text-white'
                  : 'bg-primary-600 hover:bg-primary-700 text-white shadow-primary-500/20'
              } disabled:opacity-50 disabled:cursor-not-allowed active:scale-95`}
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? t.copied : t.copy}</span>
            </button>
          </div>
        </div>

        {/* Total Invited Users Card */}
        <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-sm flex items-center justify-between">
          <div className="space-y-1">
            <p className="text-xs font-bold text-slate-500">{t.invitedAccounts}</p>
            <p className="text-3xl font-black text-slate-900">
              {stats?.totalInvitedUsers || 0}
            </p>
            <p className="text-xs font-medium text-slate-400">{t.vendorsCreators}</p>
          </div>
          <div className="w-14 h-14 rounded-2xl bg-blue-50 text-blue-600 border border-blue-100 flex items-center justify-center">
            <Users className="w-7 h-7" />
          </div>
        </div>

        {/* Delivered Leads, Earnings & Withdraw Card */}
        <div className="bg-white rounded-3xl p-6 border border-slate-200/80 shadow-sm flex flex-col justify-between space-y-3">
          <div className="flex items-center justify-between">
            <div className="space-y-1">
              <p className="text-xs font-bold text-slate-500">{t.withdrawableEarnings}</p>
              <div className="flex items-baseline gap-1">
                <p className="text-3xl font-black text-emerald-600">
                  {stats?.availableEarnings || 0} <span className="text-sm font-bold">DH</span>
                </p>
              </div>
            </div>
            <div className="w-12 h-12 rounded-2xl bg-emerald-50 text-emerald-600 border border-emerald-100 flex items-center justify-center">
              <Wallet className="w-6 h-6" />
            </div>
          </div>

          <div className="text-[11px] text-slate-500 font-medium flex items-center justify-between pt-2 border-t border-slate-100">
            <span>{t.deliveredLeads}: <strong className="text-slate-900 font-extrabold">{stats?.deliveredLeads || 0}</strong></span>
            {stats?.pendingEarnings && stats.pendingEarnings > 0 ? (
              <span className="text-amber-600 font-bold">{stats.pendingEarnings} {t.pending}</span>
            ) : null}
          </div>

          <button
            onClick={handleOpenWithdrawModal}
            disabled={!stats?.canManageAffiliateInvites || (stats?.availableEarnings || 0) < 50}
            className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-2xl bg-emerald-600 hover:bg-emerald-700 text-white font-extrabold text-xs transition-all shadow-md shadow-emerald-500/20 disabled:opacity-40 disabled:cursor-not-allowed active:scale-95"
          >
            <ArrowDownToLine className="w-4 h-4" />
            <span>
              {t.withdrawGains} {(stats?.availableEarnings || 0) < 50 ? t.min50dh : ''}
            </span>
          </button>
        </div>
      </div>

      {/* Payout Requests History Section (if any requests exist) */}
      {stats?.payoutHistory && stats.payoutHistory.length > 0 && (
        <div className="bg-white rounded-3xl border border-slate-200/80 shadow-sm overflow-hidden p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-base font-black text-slate-900 flex items-center gap-2">
              <Clock className="w-5 h-5 text-indigo-600" />
              {t.payoutHistoryTitle} ({stats.payoutHistory.length})
            </h3>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                  <th className="px-4 py-3">{t.id}</th>
                  <th className="px-4 py-3">{t.amount}</th>
                  <th className="px-4 py-3">{t.bank}</th>
                  <th className="px-4 py-3">{t.status}</th>
                  <th className="px-4 py-3 text-right">{t.date}</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs">
                {stats.payoutHistory.map((p) => (
                  <tr key={p.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-4 py-3 font-mono font-bold text-slate-500">#{p.id}</td>
                    <td className="px-4 py-3 font-black text-emerald-600 text-sm">{p.amountMad} DH</td>
                    <td className="px-4 py-3 text-slate-800 font-semibold">
                      {p.bankName} <span className="text-[10px] text-slate-400 font-mono">({p.ribAccount ? `...${p.ribAccount.slice(-6)}` : 'RIB'})</span>
                    </td>
                    <td className="px-4 py-3">
                      {p.status === 'PENDING' && (
                        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-amber-50 text-amber-700 border border-amber-200">
                          <Clock className="w-3 h-3" />
                          {t.statusPending}
                        </span>
                      )}
                      {p.status === 'COMPLETED' && (
                        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-emerald-50 text-emerald-700 border border-emerald-200">
                          <CheckCircle2 className="w-3 h-3" />
                          {t.statusCompleted}
                        </span>
                      )}
                      {p.status === 'REJECTED' && (
                        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-rose-50 text-rose-700 border border-rose-200">
                          <XCircle className="w-3 h-3" />
                          {t.statusRejected}
                        </span>
                      )}
                      {p.status === 'RECEIVED' && (
                        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-violet-50 text-violet-700 border border-violet-200">
                          <FileText className="w-3 h-3" />
                          {t.statusReceived}
                        </span>
                      )}
                      {!['PENDING', 'COMPLETED', 'REJECTED', 'RECEIVED'].includes(p.status) && (
                        <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-extrabold bg-slate-100 text-slate-600 border border-slate-200">
                          {p.status}
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-3 text-right text-slate-500 font-medium">
                      {new Date(p.createdAt).toLocaleDateString(language === 'ar' ? 'ar-MA' : language === 'en' ? 'en-US' : 'fr-FR', {
                        day: '2-digit',
                        month: 'short',
                        year: 'numeric'
                      })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Invited Accounts Table Section */}
      <div className="bg-white rounded-3xl border border-slate-200/80 shadow-sm overflow-hidden">
        {/* Table Header & Search */}
        <div className="p-6 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-lg font-black text-slate-900 flex items-center gap-2">
              <UserCheck className="w-5 h-5 text-primary-600" />
              {t.registeredUsersTitle} ({filteredUsers.length})
            </h2>
            <p className="text-xs font-medium text-slate-500">
              {t.registeredUsersDesc}
            </p>
          </div>

          <div className="relative w-full sm:w-72">
            <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder={t.searchPlaceholder}
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 rounded-2xl pl-10 pr-4 py-2.5 text-xs text-slate-800 font-medium focus:bg-white focus:outline-none focus:border-primary-500 transition-all"
            />
          </div>
        </div>

        {/* Table Content */}
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                <th className="px-6 py-4">{t.user}</th>
                <th className="px-6 py-4">{t.role}</th>
                <th className="px-6 py-4">{t.origin}</th>
                <th className="px-6 py-4">{t.regDate}</th>
                <th className="px-6 py-4 text-center">{t.totalLeads}</th>
                <th className="px-6 py-4 text-center">{t.deliveredLeadsCol}</th>
                <th className="px-6 py-4 text-right">{t.generatedComm}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-sm">
              {filteredUsers.length > 0 ? (
                filteredUsers.map((user) => (
                  <tr key={user.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-full bg-primary-100 text-primary-700 font-black flex items-center justify-center text-xs border border-primary-200">
                          {user.fullName.charAt(0).toUpperCase()}
                        </div>
                        <div>
                          <p className="font-extrabold text-slate-900 text-xs">{user.fullName}</p>
                          <p className="text-[11px] text-slate-500 font-medium">{user.email}</p>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-[11px] font-extrabold ${
                        user.role === 'VENDOR' 
                          ? 'bg-blue-50 text-blue-700 border border-blue-200/80'
                          : 'bg-purple-50 text-purple-700 border border-purple-200/80'
                      }`}>
                        {user.role === 'VENDOR' ? t.vendor : t.creator}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`whitespace-nowrap inline-flex items-center gap-1 px-3 py-1 rounded-full text-[11px] font-extrabold ${
                        user.isAffiliateInvite
                          ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                          : 'bg-slate-100 text-slate-700 border border-slate-200'
                      }`}>
                        {user.isAffiliateInvite ? t.viaLink : t.adminAssign}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-xs font-medium text-slate-500">
                      {new Date(user.createdAt).toLocaleDateString(language === 'ar' ? 'ar-MA' : language === 'en' ? 'en-US' : 'fr-FR', {
                        day: '2-digit',
                        month: 'short',
                        year: 'numeric'
                      })}
                    </td>
                    <td className="px-6 py-4 text-center font-bold text-slate-800 text-xs">
                      {user.totalLeads}
                    </td>
                    <td className="px-6 py-4 text-center">
                      <span className="inline-flex items-center gap-1 font-extrabold text-emerald-700 text-xs bg-emerald-50 px-2.5 py-1 rounded-full border border-emerald-200">
                        <PackageCheck className="w-3.5 h-3.5" />
                        {user.deliveredLeads}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right font-black text-slate-900 text-xs">
                      {user.earningsGenerated} DH
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={7} className="px-6 py-12 text-center text-slate-400">
                    <Users className="w-10 h-10 mx-auto mb-2 opacity-40" />
                    <p className="font-bold text-sm text-slate-600">{t.noUsersFound}</p>
                    <p className="text-xs text-slate-400">{t.noUsersFoundSub}</p>
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Withdrawal Modal */}
      <AnimatePresence>
        {showWithdrawModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl p-6 sm:p-8 max-w-md w-full shadow-2xl border border-slate-200 space-y-6 relative"
            >
              <button
                onClick={() => setShowWithdrawModal(false)}
                className="absolute right-5 top-5 text-slate-400 hover:text-slate-600 transition-colors"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="space-y-1">
                <div className="w-12 h-12 rounded-2xl bg-emerald-50 text-emerald-600 border border-emerald-100 flex items-center justify-center mb-3">
                  <ArrowDownToLine className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-black text-slate-900">{t.modalTitle}</h3>
                <p className="text-xs text-slate-500 font-medium">
                  {t.modalDesc}
                </p>
              </div>

              <form onSubmit={handleWithdrawSubmit} className="space-y-4">
                {/* Solde disponible badge */}
                <div className="p-3.5 rounded-2xl bg-emerald-50 border border-emerald-200 flex items-center justify-between">
                  <span className="text-xs font-bold text-emerald-800">{t.withdrawableBalance}</span>
                  <span className="text-base font-black text-emerald-700">
                    {stats?.availableEarnings || 0} DH
                  </span>
                </div>

                {/* Amount input */}
                <div>
                  <label className="block text-xs font-extrabold text-slate-800 mb-1.5">
                    {t.amountToWithdraw}
                  </label>
                  <input
                    type="number"
                    min="50"
                    max={stats?.availableEarnings || 0}
                    step="any"
                    required
                    value={withdrawAmount}
                    onChange={(e) => setWithdrawAmount(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-2xl px-4 py-3 text-sm font-bold text-slate-900 focus:bg-white focus:outline-none focus:border-primary-500 transition-all"
                    placeholder="ex: 50"
                  />
                  <p className="text-[11px] text-slate-500 mt-1 font-medium">
                    {t.minWithdrawMessage} <strong className="text-amber-600 font-bold">50 DH</strong>
                  </p>
                </div>

                {/* Bank Name */}
                <div>
                  <label className="block text-xs font-extrabold text-slate-800 mb-1.5">
                    {t.bankName}
                  </label>
                  <div className="relative">
                    <Building2 className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
                    <input
                      type="text"
                      required
                      value={bankName}
                      onChange={(e) => setBankName(e.target.value)}
                      placeholder={t.bankNamePlaceholder}
                      className="w-full bg-slate-50 border border-slate-200 rounded-2xl pl-10 pr-4 py-3 text-sm font-bold text-slate-900 focus:bg-white focus:outline-none focus:border-primary-500 transition-all"
                    />
                  </div>
                </div>

                {/* RIB Account */}
                <div>
                  <label className="block text-xs font-extrabold text-slate-800 mb-1.5">
                    {t.ribNumber}
                  </label>
                  <div className="relative">
                    <CreditCard className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
                    <input
                      type="text"
                      required
                      maxLength={24}
                      value={ribAccount}
                      onChange={(e) => setRibAccount(e.target.value.replace(/\D/g, '').slice(0, 24))}
                      placeholder="230450000000000000000000"
                      className="w-full bg-slate-50 border border-slate-200 rounded-2xl pl-10 pr-4 py-3 text-sm font-mono font-bold text-slate-900 focus:bg-white focus:outline-none focus:border-primary-500 transition-all"
                    />
                  </div>
                  <div className="flex justify-between items-center text-[11px] text-slate-400 mt-1 font-medium">
                    <span>{t.ribDigitsOnly}</span>
                    <span className={`font-mono font-bold ${ribAccount.replace(/\D/g, '').length === 24 ? 'text-emerald-600' : 'text-amber-600'}`}>
                      {ribAccount.replace(/\D/g, '').length}/24
                    </span>
                  </div>
                </div>

                <div className="pt-2 flex items-center justify-end gap-3">
                  <button
                    type="button"
                    onClick={() => setShowWithdrawModal(false)}
                    className="px-5 py-3 rounded-2xl border border-slate-200 text-xs font-bold text-slate-700 hover:bg-slate-100 transition-all"
                  >
                    {t.cancel}
                  </button>
                  <button
                    type="submit"
                    disabled={submittingWithdraw}
                    className="px-6 py-3 rounded-2xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-black shadow-lg shadow-emerald-500/20 disabled:opacity-50 flex items-center gap-2 transition-all active:scale-95"
                  >
                    {submittingWithdraw ? (
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    ) : (
                      <Check className="w-4 h-4" />
                    )}
                    <span>{t.confirmWithdrawal}</span>
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
